export const LEAVES_REPOSITORY = 'LEAVES_REPOSITORY';
export const LEAVES_SERVICE = 'LEAVES_SERVICE';
export const LEAVE_REQUESTS_REPOSITORY = 'LEAVE_REQUESTS_REPOSITORY';
export const LEAVE_REQUESTS_SERVICE = 'LEAVE_REQUESTS_SERVICE';
